/* Shared */
export enum ColorAssignment {
    white = 'white',
    black = 'black',
    dark = 'dark',
    light = 'light',
  
    primary = 'primary',
    secondary = 'secondary',
    inactive = 'inactive',
    error = 'error',
    textPrimary = 'textPrimary',
    textSecondary = 'textSecondary',
    textDark = 'textDark',
    textLight = 'textLight',
    linkHover = 'linkHover',
    pageBackground = 'pageBackground',
    burgerMenuBackground = 'burgerMenuBackground',
    burgerMenuDesktop = 'burgerMenuDesktop',
    burgerMenuDark = 'burgerMenuDark',
    burgerMenuLight = 'burgerMenuLight',
    menuBackground = 'menuBackground',
    menuLinksDark = 'menuLinksDark',
    menuLinksLight = 'menuLinksLight',
    backgroundButton = 'backgroundButton',
    textButtonOnHover = 'textButtonOnHover',
    langSelectBackground = 'langSelectBackground',
    langSelectBorder = 'langSelectBorder',
    langSelectText = 'langSelectText',
    langSelectHover = 'langSelectHover',
    footerBackground = 'footerBackground',
    footerText = 'footerText',
    footerLink = 'footerLink',
    buttonBackgroundPrimary = 'buttonBackgroundPrimary',
    buttonBorderPrimary = 'buttonBorderPrimary',
    buttonTextPrimary = 'buttonTextPrimary',
    buttonBackgroundSecondary = 'buttonBackgroundSecondary',
    buttonBorderSecondary = 'buttonBorderSecondary',
    buttonTextSecondary = 'buttonTextSecondary',
    buttonBackgroundLight = 'buttonBackgroundLight',
    buttonBorderLight = 'buttonBorderLight',
    buttonTextLight = 'buttonTextLight',
    buttonBackgroundDark = 'buttonBackgroundDark',
    buttonBorderDark = 'buttonBorderDark',
    buttonTextDark = 'buttonTextDark',
    buttonBackgroundMenu = 'buttonBackgroundMenu',
    buttonBorderMenu = 'buttonBorderMenu',
    buttonTextMenu = 'buttonTextMenu',
    buttonBackgroundFeatured = 'buttonBackgroundFeatured',
    heroHeadline = 'heroHeadline',
    heroOverlay = 'heroOverlay',
    border = 'border',
    noImageBackground = 'noImageBackground',
    sectionTagBorder = 'sectionTagBorder',
    inputBackground = 'inputBackground',
    seeAlsoBackground = 'seeAlsoBackground',
    factBoxBackground = 'factBoxBackground',
    factBoxText = 'factBoxText',
    pricingTableBorderColor = 'pricingTableBorderColor',
    pricingTableHoverColor = 'pricingTableHoverColor',
    pricingBlockOptionDefaultBackground = 'pricingBlockOptionDefaultBackground',
    pricingBlockOptionMostPopularBackground = 'pricingBlockOptionMostPopularBackground',
  }
  
  export enum FontType {
    regular = 'regular',
    semiBold = 'semiBold',
    bold = 'bold',
    variable = 'variable',
    fallback = 'fallback',
  }
  
  export enum SpacingValue {
    none = 'none',
    xsmall = 'xsmall',
    xsmallx = 'xsmallx',
    small = 'small',
    smallx = 'smallx',
    medium = 'medium',
    mediumX = 'mediumX',
    mediumXX = 'mediumXX',
    mediumXXX = 'mediumXXX',
    large = 'large',
    xlarge = 'xlarge',
    xxlarge = 'xxlarge',
  }
  
  /* GoBoat */
  export enum GBColor {
    white = 'white',
    black = 'black',
    jet = 'jet',
    charcoal = 'charcoal',
    lightGray = 'lightGray',
    gray = 'gray',
    yellow = 'yellow',
    red = 'red',
  }
  
  export enum GBFont {
    regular = 'Faro-Lucky-Regular',
    semiBold = 'Faro-Lucky-SemiBold',
    bold = 'Faro-Lucky-Bold',
    variable = 'Faro-Lucky-Variable',
    fallback = '-apple-system, BlinkMacSystemFont, Segoe UI, Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans, Helvetica Neue, sans-serif',
  }
  

